### ISSUE TITLE
pip package

### ISSUE THREAD

**Issue by rogeriopvl** [samirahmed/fu#2]
It would be interesting if fu had a [pypi](http://pypi.python.org/pypi) package so users can update to latest version with:

```
pip install fu
```

Instead of having to pull from the official repo and run python setup.

@gissues:{"order":75,"status":"backlog"}

**Comment by brainstorm** [comment]
+1

http://watson.nci.nih.gov/~sdavis/blog/quickstart_pip_and_paster/

**Comment by samirahmed** [comment]
will work on this.

**Comment by valpackett** [comment]
just setup.py uploading is considered work now?
