### ISSUE TITLE
Missing dependency - argparse

### ISSUE THREAD

**Issue by lylejantzi3rd** [samirahmed/fu#3]
If you don't use python a lot and you don't have argparse already installed, you get this when you attempt to use fu:

Traceback (most recent call last):
  File "/usr/local/bin/fu", line 5, in <module>
    pkg_resources.run_script('fu==0.1.1', 'fu')
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 442, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 1167, in run_script
    exec script_code in namespace, namespace
  File "/Library/Python/2.6/site-packages/fu-0.1.1-py2.6.egg/EGG-INFO/scripts/fu", line 19, in <module>

ImportError: No module named argparse

you should add 'easy_install argparse' to the readme file.

**Comment by Tolmark12** [comment]
(I'm also getting the above)

**Comment by samirahmed** [comment]
@lylejantzi3rd  can you confirm that 

`easy_install argparse` fixed your problem? If so I will add it to the readme right away!

**Comment by lylejantzi3rd** [comment]
It did. Proof! (I run Snow Leopard, btw, which does have python installed by default but not argparse, it seems)

☹  fu send binary mail attachment
Traceback (most recent call last):
  File "/usr/local/bin/fu", line 5, in <module>
    pkg_resources.run_script('fu==0.1.1', 'fu')
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 442, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/System/Library/Frameworks/Python.framework/Versions/2.6/Extras/lib/python/pkg_resources.py", line 1167, in run_script
    exec script_code in namespace, namespace
  File "/Library/Python/2.6/site-packages/fu-0.1.1-py2.6.egg/EGG-INFO/scripts/fu", line 19, in <module>

ImportError: No module named argparse

☹  easy_install argparse
Searching for argparse
Reading http://pypi.python.org/simple/argparse/
Reading http://code.google.com/p/argparse/
Best match: argparse 1.2.1
Downloading http://argparse.googlecode.com/files/argparse-1.2.1.tar.gz
Processing argparse-1.2.1.tar.gz
Running argparse-1.2.1/setup.py -q bdist_egg --dist-dir /var/folders/zT/zTAIEsFZEVS5qmSDT0WSe++++TM/-Tmp-/easy_install-fFTUX6/argparse-1.2.1/egg-dist-tmp-djHwYn
warning: no previously-included files matching '_.pyc' found anywhere in distribution
warning: no previously-included files matching '_.pyo' found anywhere in distribution
warning: no previously-included files matching '_.orig' found anywhere in distribution
warning: no previously-included files matching '_.rej' found anywhere in distribution
no previously-included directories found matching 'doc/_build'
no previously-included directories found matching 'env24'
no previously-included directories found matching 'env25'
no previously-included directories found matching 'env26'
no previously-included directories found matching 'env27'
zip_safe flag not set; analyzing archive contents...
Adding argparse 1.2.1 to easy-install.pth file

Installed /Library/Python/2.6/site-packages/argparse-1.2.1-py2.6.egg
Processing dependencies for argparse
Finished processing dependencies for argparse

☺  fu send binary mail attachment
 1  #  Send email with one or more binary attachments
    echo "Body goes here" | mutt -s "A subject" -a /path/to/file.tar.gz recipient@example.com

 2  #  Send a binary file as an attachment to an email
    uuencode archive.tar.gz archive.tar.gz | mail -s "Emailing: archive.tar.gz" user@example.com

```
195ms total:2
```

**Comment by samirahmed** [comment]
@lylejantzi3rd  Thanks I am appending this to the readme now
