### ISSUE TITLE
if xclip fails, try parcellite? 

### ISSUE THREAD

**Issue by dancrew32** [samirahmed/fu#5]
Feature request ahead:

`xclip` has always been a little inconsistent for me (I know this to be other linux users' experiences as well), so I use `parcellite`, which is a clipboard manager with history. 

you can just pipe text into parcellite to make it work `echo "foo" | parcellite`

if you think this doesn't belong in core, perhaps a way to configure a custom clipboard manager?

**Comment by samirahmed** [comment]
@dancrew32 - still looking for parcellite? or was your issue fixed with the last pull?

**Comment by dancrew32** [comment]
yup fixed! thanks!
