### ISSUE TITLE
Please create a version tag

### ISSUE THREAD

**Issue by whittle** [samirahmed/fu#6]
Please create a tag for this repo with a version number, so that I can add a brew recipe for fu.

**Comment by whittle** [comment]
Sorry, just saw that a download for 0.1.1 had been created, I had just missed it.

**Comment by samirahmed** [comment]
i will put a 0.1.2, please use that instead

**Comment by whittle** [comment]
Sure. Comment here when you push 0.1.2, and I’ll update my recipe.

**Comment by samirahmed** [comment]
0.1.2 is up in the downloads section

**Comment by whittle** [comment]
The 0.1.2 zip file includes 2 directories: fu and __MACOSX. It would be helpful if the __MACOSX directory were excluded.

**Comment by whittle** [comment]
It is also unnecessary (although harmless) to include the fu/.git directory in the zip.

**Comment by samirahmed** [comment]
Oops, sorry I was viewing through finder and didn't see the hidden files...

I have updated the file and removed the .git folder.

As for the __MACOSX folder, I don't know how that got in there. ket me know if the updated version follows conventions

**Comment by whittle** [comment]
I tried downloading the latest version at https://github.com/downloads/samirahmed/fu/fu_v0.1.2.zip and it still has the __MACOSX and fu/.git directories. 

Also, the convention is for the zip file to be fu-0.1.2.zip (with a hyphen and no v) and the directory that it unzips to to be fu-0.1.2 (identical to the zip file, but without an extension). This convention can be referenced at http://docs.python.org/install/index.html
