### ISSUE TITLE
README semantics

### ISSUE THREAD

**Issue by sigmavirus24** [samirahmed/fu#7]
In your README you have:

```
$ git clone git@github.com:samirahmed/fu.git
```

When in fact this is the wrong url to be suggesting someone who is not a contributor use. It should be

```
$ git clone git://github.com/samirahmed/fu.git
```

Also, you can remove the new lines in between command line examples in that so it would become:

```
$ git clone git://github.com/samirahmed/fu.git
$ cd fu/
$ sudo make install
```

and 

```
$ cd fu/
$ sudo make uninstall
```

**Comment by samirahmed** [comment]
done!
